version: "3.8"

services:
  node-app:
    image: node-app:v1
    container_name: node-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    external_links:
      - mongo
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.2.0
    volumes:
      - $PWD/data-mongo:/data/db
    ports:
      - "27017:27017"
